# Generated by Django 4.2 on 2023-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulsit', '0002_project_delete_userporfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
