# Generated by Django 4.2 on 2023-04-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulsit', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
