# Generated by Django 4.2 on 2023-04-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulsit', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
